### ISSUE TITLE
[Question] What is a changeGroup?

### ISSUE THREAD

**Issue by hmaurer** [socraticorg/mathsteps#70]
Everything is in the title! I was reading through parts of the code and wondered what a changeGroup is. I have a vague idea from where it is used but I am not quite sure; a one-sentence explanation would be amazing :-)

**Comment by evykassirer** [comment]
An excellent question!

Wanting a good answer to this question is one of the big reasons I want a wiki ( #66 ) but here's a casual short-ish explanation in the meantime...

When we were building this, we wanted to have really good descriptions of the steps. In the blog post I have a short passage that says:

> We also want to allow users of mathsteps to reference what changed specifically in the expression, for example “add 2 and 3 to make 5”. We keep track of what part of the tree changed in the node.

If you ran mathsteps on `x + 2 + 3` you'd get a single step with `step.oldNode` being the tree for `x + 2 + 3`, and `step.newNode` being the tree for `x + 5`. Also, `step.changeType` would be `SIMPLIFY_ARITHMETIC`.

In our app, we don't want the message to be "simplify arithmetic", we want it to be "add 2 + 3 to get 5" or something like that. So the `oldNode` and `newNode` need to store what part of the tree was changed. In `oldNode`, the 2 and 3 nodes in the tree have the added property `changeGroup = 1`. And in `newNode`, 5 also has `changeGroup = 1`. The change groups are indexed because for something like collecting like terms (`x + x^2 + x^2 + x -> (x^2 + x^2) + (x + x)`) it's ideal to have different change groups for the `x`s and the `x^2`s

For the most part, these change groups are added by default in `NodeStatus` creation, but sometimes custom ones are necessary (like the like terms collecting) and it's done while the change is calculated. 

Also, this change group stuff is still pretty buggy/incomplete and won't always do what's best - this is something that would be nice to eventually spend some time on and improve but there are some tricky things that make some cases pretty hard.

Hope that makes some sense - I know it's not one sentence but it's a bit complicated (which is also why I didn't talk about it in the blog post). Let me know if you have any follow-up questions!

**Comment by hmaurer** [comment]
I see; that's what I thought (I was looking for the part of the code keeping track of which nodes changed) but wasn't quite sure why it was indexed; thanks!

**Comment by nitin42** [comment]
Navigating the current codebase and would like to contribute in adding a wiki should I get to understand the whole working.
