### ISSUE TITLE
Installing mathsteps is not straightforward

### ISSUE THREAD

**Issue by kovzol** [socraticorg/mathsteps#77]
I tried several ways to install mathsteps on Ubuntu Linux 16.04.1 LTS with just partial success.

First method: "sudo apt install nodejs". It installs node 4.2.6 (which is quite old). Then by running "npm install mathsteps" a folder node_modules is created, it also includes the mathsteps/ folder. Now I tried to create a file with the example .js code with name test.js, but I get the following error when running it by "nodejs test.js":
```
/home/kovzol/workspace/node_modules/mathsteps/lib/simplifyExpression/index.js:6
function simplifyExpressionString(expressionString, debug=false) {
                                                         ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/kovzol/workspace/node_modules/mathsteps/index.js:1:90)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Second method: I built mathsteps as described on the main page. Then I copied the lib folder over the folder where the first method created mathsteps' lib folder. But I got the same error.

Third method: I downloaded newer node versions from its website. The I started "nodejs test.js" by explicitly using the correct path to the different node versions. I got the following for node version 6.9.4:
```
/home/kovzol/workspace/mathsteps-test/test.js:4
  console.log(step.oldNode.toString());    // "2 x + 2 x + x + x"
                          ^

TypeError: Cannot read property 'toString' of null
    at steps.forEach.step (/home/kovzol/workspace/mathsteps-test/test.js:4:27)
    at Array.forEach (native)
    at Object.<anonymous> (/home/kovzol/workspace/mathsteps-test/test.js:3:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```
and also the same for node version 7.4.0. It seems that step.oldNode does not exists. If I remove that line, I can make the rest work:
```
ADD_POLYNOMIAL_TERMS
6 x
3
```

**Comment by hmaurer** [comment]
For the former, it is because "default parameters" in Javascript (an ES6 feature) were not enabled by default before node 6.0.0 (I think). So you need to be running at least node 6.

For the latter, what is the content of `test.js`? It does not seem to be a file at the root of the repository; did you create it?

**Comment by hmaurer** [comment]
Ah nevermind, I guess you copied the example script from the README into a `test.js` file. As far as I can tell there is either a mistake in the example or in the codebase. The property `oldNode` is null in the first step, however it is present in all the substeps. @evykassirer

**Comment by hmaurer** [comment]
After taking a look it seems it's due to some weirdness with [Status.reset](https://github.com/socraticorg/mathsteps/blob/master/lib/node/Status.js#L31). When calling `nodeStatus.reset()` [here](https://github.com/socraticorg/mathsteps/blob/master/lib/simplifyExpression/stepThrough.js#L46) it sets the `oldNode` property of the object that has just been pushed to `steps` to `null`.

I suspect this bug was not present at the time of [this commit](https://github.com/socraticorg/mathsteps/blob/8cabb78a815102642dedb4e7388e516be5ef6217/lib/simplifyExpression/stepThrough.js#L43) because it was [manually cloning the node status](https://github.com/socraticorg/mathsteps/blob/8cabb78a815102642dedb4e7388e516be5ef6217/lib/simplifyExpression/stepThrough.js#L115). This might explain why the example does not reflect what's actually going on :-)

**Comment by evykassirer** [comment]
1. Yeah, you nee at least node 6 for default parameters. I'll open an issue to add that to the documentation.

2. Okay yeah that's our fault. You have it installed correctly. We'll fix that bug and release a new version on npm :) 

Thanks so much @kovzol for bringing both these issues up and @hmaurer for investigating :)

**Comment by kovzol** [comment]
Thank you for the prompt reply!

**Comment by evykassirer** [comment]
(fix made, reopening until I publish a new version of npm)

**Comment by evykassirer** [comment]
should be fixed now! please re-open this issue if you have any further problems with this.

thanks again for letting us know and @hmaurer and @Raibaz for fixing 😄
